//! Performance counter for all Intel architectures.
use super::description::{Counter, EventDescription, MSRIndex, PebsType, Tuple};
/// The content of this file is automatically generated by `build.rs`
/// from the data in `x86data/perfmon_data`.
use phf;

include!(concat!(env!("OUT_DIR"), "/counters.rs"));
